/* This file is generated by scripts/import-exercise-videos.mjs. */

export interface ExerciseVideo {
  source: number
  title: string
  sourceName: string
  sourceUrl: string
  licenseName: string
  licenseUrl: string
  attribution: string
}

export const EXERCISE_VIDEO_IDS = [
  "Barbell_Curl",
  "Barbell_Hip_Thrust",
  "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "Barbell_Lunge",
  "Barbell_Walking_Lunge",
  "bench-press",
  "Bent_Over_Barbell_Row",
  "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
  "Cable_Hammer_Curls_-_Rope_Attachment",
  "Cable_One_Arm_Tricep_Extension",
  "deadlift",
  "Dips_-_Triceps_Version",
  "Dumbbell_Bench_Press",
  "Dumbbell_Bicep_Curl",
  "Dumbbell_Lunges",
  "Dumbbell_Shoulder_Press",
  "EZ-Bar_Skullcrusher",
  "Face_Pull",
  "Front_Barbell_Squat",
  "Hack_Squat",
  "Hammer_Curls",
  "Incline_Dumbbell_Press",
  "Leg_Extensions",
  "Leg_Press",
  "Leverage_Chest_Press",
  "Low_Cable_Crossover",
  "Lying_Dumbbell_Tricep_Extension",
  "Lying_Leg_Curls",
  "Machine_Shoulder_Military_Press",
  "One_Arm_Dumbbell_Preacher_Curl",
  "overhead-press",
  "plank",
  "Preacher_Curl",
  "pull-up",
  "Romanian_Deadlift",
  "Seated_Cable_Rows",
  "Seated_Calf_Raise",
  "Seated_Leg_Curl",
  "Side_Lateral_Raise",
  "Smith_Machine_Behind_the_Back_Shrug",
  "Smith_Machine_Squat",
  "squat",
  "Standing_Biceps_Cable_Curl",
  "Standing_Calf_Raises",
  "Standing_Dumbbell_Triceps_Extension",
  "Standing_Leg_Curl",
  "Thigh_Adductor",
  "Tricep_Dumbbell_Kickback",
  "Triceps_Pushdown",
  "Wide-Grip_Lat_Pulldown",
] as const

export function getGeneratedExerciseVideo(exerciseId: string): ExerciseVideo | undefined {
  switch (exerciseId) {
    case "Barbell_Curl":
      return {
        source: require("../../assets/exercise-videos/Barbell_Curl.mp4"),
        title: "Barbell Curls",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Barbell_Hip_Thrust":
      return {
        source: require("../../assets/exercise-videos/Barbell_Hip_Thrust.mp4"),
        title: "Barbell Hip Thrust",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Barbell_Incline_Bench_Press_-_Medium_Grip":
      return {
        source: require("../../assets/exercise-videos/Barbell_Incline_Bench_Press_-_Medium_Grip.mp4"),
        title: "Wger exercise 538",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/538/4349a6f6-4cee-4c09-828b-c5e7fc2c1ff1.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Barbell_Lunge":
      return {
        source: require("../../assets/exercise-videos/Barbell_Lunge.mp4"),
        title: "Wger exercise 46",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/46/d45df7af-586b-42d0-bc56-d1e028812f12.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Barbell_Walking_Lunge":
      return {
        source: require("../../assets/exercise-videos/Barbell_Walking_Lunge.mp4"),
        title: "Wger exercise 802",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/802/85d1d7f8-c3c5-47e8-9b26-56896919e6e7.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "bench-press":
      return {
        source: require("../../assets/exercise-videos/bench-press.mp4"),
        title: "Bench Press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Bent_Over_Barbell_Row":
      return {
        source: require("../../assets/exercise-videos/Bent_Over_Barbell_Row.mp4"),
        title: "Barbell Rows",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench":
      return {
        source: require("../../assets/exercise-videos/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench.mp4"),
        title: "Wger exercise 82",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/82/28b53647-27e7-47cf-8852-2ee666c8b628.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Cable_Hammer_Curls_-_Rope_Attachment":
      return {
        source: require("../../assets/exercise-videos/Cable_Hammer_Curls_-_Rope_Attachment.mp4"),
        title: "Wger exercise 275",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/275/af1fff93-eb58-4ba7-97a4-b38ee67853b4.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Cable_One_Arm_Tricep_Extension":
      return {
        source: require("../../assets/exercise-videos/Cable_One_Arm_Tricep_Extension.mp4"),
        title: "Wger exercise 803",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/803/99e0001f-217a-4b11-823c-014d24a5415e.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "deadlift":
      return {
        source: require("../../assets/exercise-videos/deadlift.mp4"),
        title: "Barbell Deadlift",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Dips_-_Triceps_Version":
      return {
        source: require("../../assets/exercise-videos/Dips_-_Triceps_Version.mp4"),
        title: "Wger exercise 194",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/194/dd9a663f-d8ba-4621-823b-13788ccb66bc.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Dumbbell_Bench_Press":
      return {
        source: require("../../assets/exercise-videos/Dumbbell_Bench_Press.mp4"),
        title: "Wger exercise 75",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/75/080c799b-8afd-4130-8d72-9cef0cd79f54.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Dumbbell_Bicep_Curl":
      return {
        source: require("../../assets/exercise-videos/Dumbbell_Bicep_Curl.mp4"),
        title: "Dumbbell Bicep Curl Standing",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Dumbbell_Lunges":
      return {
        source: require("../../assets/exercise-videos/Dumbbell_Lunges.mp4"),
        title: "Dumbbell Lunges",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Dumbbell_Shoulder_Press":
      return {
        source: require("../../assets/exercise-videos/Dumbbell_Shoulder_Press.mp4"),
        title: "Dumbbell Shoulder Press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "EZ-Bar_Skullcrusher":
      return {
        source: require("../../assets/exercise-videos/EZ-Bar_Skullcrusher.mp4"),
        title: "Wger exercise 246",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/246/2a194d11-ff5d-4bdf-849e-1c441cf7b0b1.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Face_Pull":
      return {
        source: require("../../assets/exercise-videos/Face_Pull.mp4"),
        title: "Cable Rope Face Pull",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Front_Barbell_Squat":
      return {
        source: require("../../assets/exercise-videos/Front_Barbell_Squat.mp4"),
        title: "Wger exercise 257",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/257/93145935-29db-4e52-9d2d-174b1c30c098.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Hack_Squat":
      return {
        source: require("../../assets/exercise-videos/Hack_Squat.mp4"),
        title: "Wger exercise 375",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/375/effa7a81-dbdd-4014-83ee-ddf0fd835301.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Hammer_Curls":
      return {
        source: require("../../assets/exercise-videos/Hammer_Curls.mp4"),
        title: "Wger exercise 272",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/272/df069052-2173-4f24-855f-a0eebe729f24.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Incline_Dumbbell_Press":
      return {
        source: require("../../assets/exercise-videos/Incline_Dumbbell_Press.mp4"),
        title: "Incline Dumbbell Press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Leg_Extensions":
      return {
        source: require("../../assets/exercise-videos/Leg_Extensions.mp4"),
        title: "Leg Extension",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Leg_Press":
      return {
        source: require("../../assets/exercise-videos/Leg_Press.mp4"),
        title: "Leg Press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Leverage_Chest_Press":
      return {
        source: require("../../assets/exercise-videos/Leverage_Chest_Press.mp4"),
        title: "Seated Machine Chest Press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Low_Cable_Crossover":
      return {
        source: require("../../assets/exercise-videos/Low_Cable_Crossover.mp4"),
        title: "Low Cable Crossover",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Lying_Dumbbell_Tricep_Extension":
      return {
        source: require("../../assets/exercise-videos/Lying_Dumbbell_Tricep_Extension.mp4"),
        title: "Wger exercise 245",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/245/c253303e-9160-4f1f-b4fe-daf1e6c8661d.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Lying_Leg_Curls":
      return {
        source: require("../../assets/exercise-videos/Lying_Leg_Curls.mp4"),
        title: "Lying Leg Curl",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Machine_Shoulder_Military_Press":
      return {
        source: require("../../assets/exercise-videos/Machine_Shoulder_Military_Press.mp4"),
        title: "Wger exercise 543",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/543/dbfd396b-1aab-4a64-a50b-2c31ff0a2cf7.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "One_Arm_Dumbbell_Preacher_Curl":
      return {
        source: require("../../assets/exercise-videos/One_Arm_Dumbbell_Preacher_Curl.mp4"),
        title: "Wger exercise 584",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/584/109e8d5d-62a4-40ad-8813-2ccef5bc751f.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "overhead-press":
      return {
        source: require("../../assets/exercise-videos/overhead-press.mp4"),
        title: "Shoulder press - Overhead press - Military press",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "plank":
      return {
        source: require("../../assets/exercise-videos/plank.mp4"),
        title: "Plank",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Preacher_Curl":
      return {
        source: require("../../assets/exercise-videos/Preacher_Curl.mp4"),
        title: "Wger exercise 465",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/465/5d2339a4-815f-46ba-aa19-8a763cfdeba0.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "pull-up":
      return {
        source: require("../../assets/exercise-videos/pull-up.mp4"),
        title: "Normal grip pull ups (Full range of motion",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Romanian_Deadlift":
      return {
        source: require("../../assets/exercise-videos/Romanian_Deadlift.mp4"),
        title: "Romanian Deadlift",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Seated_Cable_Rows":
      return {
        source: require("../../assets/exercise-videos/Seated_Cable_Rows.mp4"),
        title: "Seated Cable Row Neutral Grip",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Seated_Calf_Raise":
      return {
        source: require("../../assets/exercise-videos/Seated_Calf_Raise.mp4"),
        title: "Seated Calf Raise Machine",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Seated_Leg_Curl":
      return {
        source: require("../../assets/exercise-videos/Seated_Leg_Curl.mp4"),
        title: "Wger exercise 366",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/366/43df4b79-d4c3-4fbf-bcb5-e0d825b84120.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Side_Lateral_Raise":
      return {
        source: require("../../assets/exercise-videos/Side_Lateral_Raise.mp4"),
        title: "Side Lateral Raise with Dumbbells",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Smith_Machine_Behind_the_Back_Shrug":
      return {
        source: require("../../assets/exercise-videos/Smith_Machine_Behind_the_Back_Shrug.mp4"),
        title: "Wger exercise 575",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/575/a7d99f2b-86fc-433a-8ab1-83144c802296.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Smith_Machine_Squat":
      return {
        source: require("../../assets/exercise-videos/Smith_Machine_Squat.mp4"),
        title: "Wger exercise 341",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/341/0cbfeace-dda9-4166-8424-f51358e88a4f.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "squat":
      return {
        source: require("../../assets/exercise-videos/squat.mp4"),
        title: "Barbell Back Squat",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Standing_Biceps_Cable_Curl":
      return {
        source: require("../../assets/exercise-videos/Standing_Biceps_Cable_Curl.mp4"),
        title: "Wger exercise 95",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/95/ab770931-47d3-44fd-aef0-ac7a64c3b794.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Standing_Calf_Raises":
      return {
        source: require("../../assets/exercise-videos/Standing_Calf_Raises.mp4"),
        title: "Wger exercise 622",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/622/461171e5-2b16-407d-bf27-27aeef43f105.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Standing_Dumbbell_Triceps_Extension":
      return {
        source: require("../../assets/exercise-videos/Standing_Dumbbell_Triceps_Extension.mp4"),
        title: "Wger exercise 211",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/211/85f6eb25-a76c-409e-9af9-497794ac0dfb.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Standing_Leg_Curl":
      return {
        source: require("../../assets/exercise-videos/Standing_Leg_Curl.mp4"),
        title: "Wger exercise 367",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/367/e8113ae4-a0b4-42a2-8eaa-3263de64622e.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Thigh_Adductor":
      return {
        source: require("../../assets/exercise-videos/Thigh_Adductor.mp4"),
        title: "Wger exercise 12",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/12/5148c579-5df2-4618-9a7b-a2e29ac4dd7d.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Tricep_Dumbbell_Kickback":
      return {
        source: require("../../assets/exercise-videos/Tricep_Dumbbell_Kickback.mp4"),
        title: "Wger exercise 655",
        sourceName: "Wger Workout Manager",
        sourceUrl:
          "https://wger.de/media/exercise-video/655/2d88a05b-bde3-4026-bfbf-524c11068dc5.MOV",
        licenseName: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Goulart",
      }
    case "Triceps_Pushdown":
      return {
        source: require("../../assets/exercise-videos/Triceps_Pushdown.mp4"),
        title: "Cable Tricep Pushdown",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    case "Wide-Grip_Lat_Pulldown":
      return {
        source: require("../../assets/exercise-videos/Wide-Grip_Lat_Pulldown.mp4"),
        title: "Lat Pulldown",
        sourceName: "YMove",
        sourceUrl: "https://ymove.app/free-exercise-videos",
        licenseName: "Royalty-free commercial use",
        licenseUrl: "https://ymove.app/free-exercise-videos",
        attribution: "YMove",
      }
    default:
      return undefined
  }
}
